version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: insurance-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: